set (SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)

list(APPEND MODULE_TESTABLE_SOURCES
    ${SRC_DIR}/sleep.h
    ${SRC_DIR}/utils.c
    ${SRC_DIR}/utils.h
    ${SRC_DIR}/error_codes.c
    ${SRC_DIR}/error_codes.h 
)

list(APPEND MODULE_NON_TESTABLE_SOURCES
)


list(APPEND MODULE_TESTABLE_INCLUDE_DIRS
    ${SRC_DIR})

list(APPEND MODULE_NON_TESTABLE_INCLUDE_DIRS )


# propagate variables with names to the parent scope
set(TESTABLE_SOURCES ${MODULE_TESTABLE_SOURCES} PARENT_SCOPE)
set(NON_TESTABLE_SOURCES ${MODULE_NON_TESTABLE_SOURCES} PARENT_SCOPE)
set(TESTABLE_INCLUDE_DIRS ${MODULE_TESTABLE_INCLUDE_DIRS} PARENT_SCOPE)
set(NON_TESTABLE_INCLUDE_DIRS ${MODULE_NON_TESTABLE_INCLUDE_DIRS} PARENT_SCOPE)

