set (SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)

list(APPEND MODULE_TESTABLE_SOURCES
    ${SRC_DIR}/mill_zigbee.h
    ${SRC_DIR}/mill_zigbee.cpp
)

list(APPEND MODULE_NON_TESTABLE_SOURCES)

list(APPEND MODULE_TESTABLE_INCLUDE_DIRS
    ${SRC_DIR})

list(APPEND MODULE_NON_TESTABLE_INCLUDE_DIRS )


# propagate variables with names to the parent scope
set(TESTABLE_SOURCES ${MODULE_TESTABLE_SOURCES} PARENT_SCOPE)
set(NON_TESTABLE_SOURCES ${MODULE_NON_TESTABLE_SOURCES} PARENT_SCOPE)
set(TESTABLE_INCLUDE_DIRS ${MODULE_TESTABLE_INCLUDE_DIRS} PARENT_SCOPE)
set(NON_TESTABLE_INCLUDE_DIRS ${MODULE_NON_TESTABLE_INCLUDE_DIRS} PARENT_SCOPE)

